// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type AddBookInput struct {
	Title       string       `json:"title" bson:"title"`
	Author      string       `json:"author" bson:"author"`
	Category    BookCategory `json:"category" bson:"category"`
	Description string       `json:"description" bson:"description"`
	Isbn        string       `json:"isbn" bson:"isbn"`
	CoverImage  string       `json:"coverImage" bson:"coverImage"`
}

type Admin struct {
	ID    string `json:"id" bson:"_id"`
	Name  string `json:"name" bson:"name"`
	Email string `json:"email" bson:"email"`
}

type AdminDashboard struct {
	TotalBooks  *int         `json:"totalBooks,omitempty" bson:"totalBooks"`
	TotalUsers  *int         `json:"totalUsers,omitempty" bson:"totalUsers"`
	BorrowStats *BorrowStats `json:"borrowStats,omitempty" bson:"borrowStats"`
}

type AdminInput struct {
	Name     string `json:"name" bson:"name"`
	Email    string `json:"email" bson:"email"`
	Password string `json:"password" bson:"password"`
}

type AuthPayload struct {
	Token string `json:"token" bson:"token"`
	User  *User  `json:"user" bson:"user"`
}

type Book struct {
	ID           string           `json:"id" bson:"_id"`
	Title        string           `json:"title" bson:"title"`
	Author       string           `json:"author" bson:"author"`
	Category     BookCategory     `json:"category" bson:"category"`
	Description  string           `json:"description" bson:"description"`
	Isbn         string           `json:"isbn" bson:"isbn"`
	CoverImage   string           `json:"coverImage" bson:"coverImage"`
	Availability BookAvailability `json:"availability" bson:"availability"`
	Rating       float64          `json:"rating" bson:"rating"`
	Reviews      []*Review        `json:"reviews,omitempty" bson:"reviews"`
}

type BookHistory struct {
	Book         *Book   `json:"book,omitempty" bson:"book"`
	BorrowedDate *string `json:"borrowedDate,omitempty" bson:"borrowedDate"`
	ReturnedDate *string `json:"returnedDate,omitempty" bson:"returnedDate"`
}

type Bookmark struct {
	Book *Book `json:"book" bson:"book"`
	Page int   `json:"page" bson:"page"`
}

type BorrowReceipt struct {
	Book    *Book  `json:"book" bson:"book"`
	DueDate string `json:"dueDate" bson:"dueDate"`
}

type BorrowStats struct {
	Daily   *int `json:"daily,omitempty" bson:"daily"`
	Weekly  *int `json:"weekly,omitempty" bson:"weekly"`
	Monthly *int `json:"monthly,omitempty" bson:"monthly"`
}

type DateRangeInput struct {
	StartDate string `json:"startDate" bson:"startDate"`
	EndDate   string `json:"endDate" bson:"endDate"`
}

type Discussion struct {
	ID        string             `json:"id" bson:"_id"`
	Title     string             `json:"title" bson:"title"`
	Category  string             `json:"category" bson:"category"`
	Replies   []*DiscussionReply `json:"replies,omitempty" bson:"replies"`
	CreatedAt *string            `json:"createdAt,omitempty" bson:"createdAt"`
	CreatedBy *User              `json:"createdBy" bson:"createdBy"`
}

type DiscussionInput struct {
	Title    string `json:"title" bson:"title"`
	Category string `json:"category" bson:"category"`
	Content  string `json:"content" bson:"content"`
}

type DiscussionReply struct {
	ID        string  `json:"id" bson:"_id"`
	Content   string  `json:"content" bson:"content"`
	CreatedAt *string `json:"createdAt,omitempty" bson:"createdAt"`
	CreatedBy *User   `json:"createdBy" bson:"createdBy"`
}

type EditBookInput struct {
	Title       *string       `json:"title,omitempty" bson:"title"`
	Author      *string       `json:"author,omitempty" bson:"author"`
	Category    *BookCategory `json:"category,omitempty" bson:"category"`
	Description *string       `json:"description,omitempty" bson:"description"`
	Isbn        *string       `json:"isbn,omitempty" bson:"isbn"`
	CoverImage  *string       `json:"coverImage,omitempty" bson:"coverImage"`
}

type Library struct {
	BorrowedBooks  []*Book `json:"borrowedBooks,omitempty" bson:"borrowedBooks"`
	ReservedBooks  []*Book `json:"reservedBooks,omitempty" bson:"reservedBooks"`
	PurchasedBooks []*Book `json:"purchasedBooks,omitempty" bson:"purchasedBooks"`
	FavoriteBooks  []*Book `json:"favoriteBooks,omitempty" bson:"favoriteBooks"`
}

type Mutation struct {
}

type Notification struct {
	ID        string  `json:"id" bson:"_id"`
	Type      string  `json:"type" bson:"type"`
	Message   string  `json:"message" bson:"message"`
	CreatedAt *string `json:"createdAt,omitempty" bson:"createdAt"`
	Read      *bool   `json:"read,omitempty" bson:"read"`
}

type NotificationSettings struct {
	DueDateReminders  *bool `json:"dueDateReminders,omitempty" bson:"dueDateReminders"`
	NewArrivals       *bool `json:"newArrivals,omitempty" bson:"newArrivals"`
	CommunityActivity *bool `json:"communityActivity,omitempty" bson:"communityActivity"`
}

type NotificationSettingsInput struct {
	DueDateReminders  *bool `json:"dueDateReminders,omitempty" bson:"dueDateReminders,omitempty"`
	NewArrivals       *bool `json:"newArrivals,omitempty" bson:"newArrivals,omitempty"`
	CommunityActivity *bool `json:"communityActivity,omitempty" bson:"communityActivity,omitempty"`
}

type PaymentDetails struct {
	Method        string `json:"method" bson:"method"`
	TransactionID string `json:"transactionId" bson:"transactionId"`
}

type PaymentInput struct {
	Method     string  `json:"method" bson:"method"`
	CardNumber *string `json:"cardNumber,omitempty" bson:"cardNumber,omitempty"`
	ExpiryDate *string `json:"expiryDate,omitempty" bson:"expiryDate,omitempty"`
	Cvv        *string `json:"cvv,omitempty" bson:"cvv,omitempty"`
}

type PurchaseReceipt struct {
	Book           *Book           `json:"book" bson:"book"`
	Price          float64         `json:"price" bson:"price"`
	PaymentDetails *PaymentDetails `json:"paymentDetails" bson:"paymentDetails"`
}

type Query struct {
}

type Report struct {
	ID          string `json:"id" bson:"_id,omitempty"`
	Title       string `json:"title" bson:"title"`
	GeneratedAt string `json:"generatedAt" bson:"generatedAt"`
	Data        string `json:"data" bson:"data"`
}

type ReportFilterInput struct {
	DateRange    *DateRangeInput `json:"dateRange,omitempty" bson:"dateRange,omitempty"`
	Category     *BookCategory   `json:"category,omitempty" bson:"category,omitempty"`
	UserActivity *string         `json:"userActivity,omitempty" bson:"userActivity,omitempty"`
}

type ReserveReceipt struct {
	Book            *Book  `json:"book" bson:"book"`
	ReservationDate string `json:"reservationDate" bson:"reservationDate"`
}

type Review struct {
	ID        string  `json:"id" bson:"_id,omitempty"`
	User      *User   `json:"user" bson:"user"`
	Book      *Book   `json:"book" bson:"book"`
	Rating    float64 `json:"rating" bson:"rating"`
	Content   *string `json:"content,omitempty" bson:"content,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty" bson:"createdAt,omitempty"`
}

type ReviewInput struct {
	Rating  float64 `json:"rating" bson:"rating"`
	Content *string `json:"content,omitempty" bson:"content,omitempty"`
}

type SignUpInput struct {
	Name           string          `json:"name" bson:"name"`
	Email          string          `json:"email" bson:"email"`
	Password       string          `json:"password" bson:"password"`
	FavoriteGenres []*BookCategory `json:"favoriteGenres,omitempty" bson:"favoriteGenres,omitempty"`
}

type UpdateProfileInput struct {
	Name           *string         `json:"name,omitempty" bson:"name,omitempty"`
	Email          *string         `json:"email,omitempty" bson:"email,omitempty"`
	FavoriteGenres []*BookCategory `json:"favoriteGenres,omitempty" bson:"favoriteGenres,omitempty"`
}

type User struct {
	ID             string             `json:"id" bson:"_id"`
	Name           string             `json:"name" bson:"name"`
	Email          string             `json:"email" bson:"email"`
	Password       string             `json:"password" bson:"password"`
	FavoriteGenres []*BookCategory    `json:"favoriteGenres,omitempty" bson:"favoriteGenres"`
	ActivityStats  *UserActivityStats `json:"activityStats,omitempty" bson:"activityStats"`
	Role           UserRole           `json:"role" bson:"role"`
}

type UserActivityStats struct {
	BooksBorrowed  *int `json:"booksBorrowed,omitempty" bson:"booksBorrowed,omitempty"`
	ReviewsWritten *int `json:"reviewsWritten,omitempty" bson:"reviewsWritten,omitempty"`
}

type UserProfile struct {
	User           *User              `json:"user" bson:"user"`
	FavoriteGenres []*BookCategory    `json:"favoriteGenres,omitempty" bson:"favoriteGenres,omitempty"`
	ActivityStats  *UserActivityStats `json:"activityStats,omitempty" bson:"activityStats,omitempty"`
}

type BookAvailability string

const (
	BookAvailabilityAvailable BookAvailability = "AVAILABLE"
	BookAvailabilityReserved  BookAvailability = "RESERVED"
	BookAvailabilityBorrowed  BookAvailability = "BORROWED"
	BookAvailabilitySoldOut   BookAvailability = "SOLD_OUT"
)

var AllBookAvailability = []BookAvailability{
	BookAvailabilityAvailable,
	BookAvailabilityReserved,
	BookAvailabilityBorrowed,
	BookAvailabilitySoldOut,
}

func (e BookAvailability) IsValid() bool {
	switch e {
	case BookAvailabilityAvailable, BookAvailabilityReserved, BookAvailabilityBorrowed, BookAvailabilitySoldOut:
		return true
	}
	return false
}

func (e BookAvailability) String() string {
	return string(e)
}

func (e *BookAvailability) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookAvailability(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookAvailability", str)
	}
	return nil
}

func (e BookAvailability) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type BookCategory string

const (
	BookCategoryFiction        BookCategory = "FICTION"
	BookCategoryNonFiction     BookCategory = "NON_FICTION"
	BookCategoryScienceFiction BookCategory = "SCIENCE_FICTION"
	BookCategoryFantasy        BookCategory = "FANTASY"
	BookCategoryMystery        BookCategory = "MYSTERY"
	BookCategoryRomance        BookCategory = "ROMANCE"
	BookCategoryThriller       BookCategory = "THRILLER"
	BookCategoryBiography      BookCategory = "BIOGRAPHY"
	BookCategoryHistory        BookCategory = "HISTORY"
	BookCategoryScience        BookCategory = "SCIENCE"
	BookCategorySelfHelp       BookCategory = "SELF_HELP"
	BookCategoryChildren       BookCategory = "CHILDREN"
)

var AllBookCategory = []BookCategory{
	BookCategoryFiction,
	BookCategoryNonFiction,
	BookCategoryScienceFiction,
	BookCategoryFantasy,
	BookCategoryMystery,
	BookCategoryRomance,
	BookCategoryThriller,
	BookCategoryBiography,
	BookCategoryHistory,
	BookCategoryScience,
	BookCategorySelfHelp,
	BookCategoryChildren,
}

func (e BookCategory) IsValid() bool {
	switch e {
	case BookCategoryFiction, BookCategoryNonFiction, BookCategoryScienceFiction, BookCategoryFantasy, BookCategoryMystery, BookCategoryRomance, BookCategoryThriller, BookCategoryBiography, BookCategoryHistory, BookCategoryScience, BookCategorySelfHelp, BookCategoryChildren:
		return true
	}
	return false
}

func (e BookCategory) String() string {
	return string(e)
}

func (e *BookCategory) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookCategory", str)
	}
	return nil
}

func (e BookCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserRole string

const (
	UserRoleReader UserRole = "READER"
	UserRoleAdmin  UserRole = "ADMIN"
)

var AllUserRole = []UserRole{
	UserRoleReader,
	UserRoleAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleReader, UserRoleAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
